version: '3.8'

services:
  mongo:
    image: mongo
    container_name: aircraftDB
    ports:
      - "27018:27018"
    volumes:
      - mongo_data:/data/db

  microservice:
    build: .
    container_name: microservice_aircraft
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27018/aircraftDB

volumes:
  mongo_data:
